### PR TITLE
Add option to set display name to service name

### LINKED ISSUE #119: Visibility of alerts with same servicename in Nagstamon
Now Signalilo creates unique services with IDs based on: `${alertname}_${fingerprint}` and give them names as: `${alertname}` to have more nice output in Web UI, but when Icinga used as server in Nagstamon this results in the fact that Nagstamon will display only 1 alert from a bunch of alerts with same servicename.

It would be cool if Signalilo could support an optional workaround for it:
- set display service name as `${alertname}_${fingerprint}`
- set servicename as-is

This logic could be controlled by a command flag or environment variable, while by default it will work as-is.

Additionally, support nice servicename as `${alertname}_${id}`, where `${id}` is an incremental integer? Would be cool, but not sure it's possible or worth the effort. As it means that we need to check for any existing `${alertname}_${id}` before creating alert, not think Icinga could return service not by its IDs, but by display servicename. Maybe a sort of search request with filter by `${alertname}_` is possible?

Thank you in advance!

### PR DESCRIPTION
**Pull request by dragoangel**
Resolves #119 

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the README.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Link this PR to related issues.

### CODE REVIEW

**Comment by dragoangel** [comment]
It will allow see multiply alerts in Nagstamon like this:
image

**Review by simu — COMMENTED** [review]
Thanks for the contribution, LGTM overall.

I'll quickly test this locally, and will merge and release if there's no issues.

**Comment by dragoangel** [comment]
Hi @simu, can you add a new release tag to docker image and update the helm chart repo version, please? Thank you for quick code review.

**Comment by simu** [comment]
@dragoangel I've now created a new release tag (v0.13.0). If you're using Helm, you should be able to use the new flag through Helm value `extraEnvVars`.

**Comment by dragoangel** [comment]
> @dragoangel I've now created a new release tag (v0.13.0). If you're using Helm, you should be able to use the new flag through Helm value `extraEnvVars`.

Thank you 👍, yes I yesterday already used extraEnvVars with the latest flag and before it used own repo for test.

**Pull request merged**
